# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024 Andalib Bin Haque <pollob666@gmail.com>

name: fuel_tracker
description: "Fuel Consumption Tracker by https://github.com/pollob666"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 2.0.8+8

# The following defines the environment constraints for your application.
environment:
  sdk: '>=3.6.2 <4.0.0'

# Application dependencies
dependencies:
  # Core Flutter packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8 # Kept for potential iOS-style icons.
  dynamic_color: ^1.8.1 # For dynamic theming based on user's wallpaper (Android 12+).

  # Data & Storage
  csv: ^6.0.0
  file_picker: ^10.3.8
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2

  # Internationalization
  intl: ^0.20.2

  # Networking & Versioning
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  google_mobile_ads: ^7.0.0
  version: ^3.0.2


# Development-only dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Generates launcher icons for Android and iOS.

# Flutter-specific configurations
flutter:
  generate: true # Enables generation of AppLocalizations using `flutter gen-l10n`.
  uses-material-design: true

  assets:
    - assets/fuelTracker.png
    - assets/dash.png

# Launcher icon configuration (uses the `flutter_launcher_icons` package).
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/fuelTracker.png"
